CREATE TABLE CHAIR (
    ID NUMBER(3) PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    PHONE VARCHAR2(20)
);

INSERT INTO CHAIR (ID, NAME, PHONE) VALUES (1, 'ЮНЕСКО по ИВТ', '546469');
INSERT INTO CHAIR (ID, NAME, PHONE) VALUES (2, 'Прикладной математики', '543470');
INSERT INTO CHAIR (ID, NAME, PHONE) VALUES (3, 'Фундаментальной математики', '543418');
INSERT INTO CHAIR (ID, NAME, PHONE) VALUES (4, 'Техносферной безопасности', '396844');
INSERT INTO CHAIR (ID, NAME, PHONE) VALUES (5, 'Геологии и географии', '580166');
INSERT INTO CHAIR (ID, NAME, PHONE) VALUES (6, 'Русского языка и литературы', '582745');
INSERT INTO CHAIR (ID, NAME, PHONE) VALUES (7, 'Истории России', '584016');
INSERT INTO CHAIR (ID, NAME, PHONE) VALUES (8, 'Международного права', '776785');

CREATE TABLE LECTURER (
    ID NUMBER(3) PRIMARY KEY,
    LAST_NAME VARCHAR2(20) NOT NULL,
    FIRST_NAME VARCHAR2(20),
    SCIENT_DEGREE VARCHAR2(15),
    ACADEM_STATUS VARCHAR2(15),
    START_DATE VARCHAR2(15) NOT NULL,
    CHAIR_ID NUMBER(3),
    CONSTRAINT fk_lecturer_chair FOREIGN KEY (CHAIR_ID) REFERENCES CHAIR(ID)
);

INSERT INTO LECTURER (ID, LAST_NAME, FIRST_NAME, SCIENT_DEGREE, ACADEM_STATUS, START_DATE, CHAIR_ID)
VALUES (1, 'Стуколов', 'Сергей', 'кандидат', 'доцент', '06.09.2000', 1);
INSERT INTO LECTURER (ID, LAST_NAME, FIRST_NAME, SCIENT_DEGREE, ACADEM_STATUS, START_DATE, CHAIR_ID)
VALUES (2, 'Фомина', 'Любовь', 'кандидат', 'доцент', '23.08.2004', 1);
INSERT INTO LECTURER (ID, LAST_NAME, FIRST_NAME, SCIENT_DEGREE, ACADEM_STATUS, START_DATE, CHAIR_ID)
VALUES (3, 'Завозкин', 'Сергей', 'кандидат', 'доцент', '30.08.2006', 1);
INSERT INTO LECTURER (ID, LAST_NAME, FIRST_NAME, SCIENT_DEGREE, ACADEM_STATUS, START_DATE, CHAIR_ID)
VALUES (4, 'Данилов', 'Николай', 'доктор', 'профессор', '15.03.1991', 2);
INSERT INTO LECTURER (ID, LAST_NAME, FIRST_NAME, SCIENT_DEGREE, ACADEM_STATUS, START_DATE, CHAIR_ID)
VALUES (5, 'Неверов', 'Евгений', 'доктор', 'профессор', '16.02.1995', 4);
INSERT INTO LECTURER (ID, LAST_NAME, FIRST_NAME, SCIENT_DEGREE, ACADEM_STATUS, START_DATE, CHAIR_ID)
VALUES (6, 'Умрихин', 'Анатолий', 'кандидат', 'доцент', '24.07.1975', 4);
INSERT INTO LECTURER (ID, LAST_NAME, FIRST_NAME, SCIENT_DEGREE, ACADEM_STATUS, START_DATE, CHAIR_ID)
VALUES (7, 'Кирсанов', 'Михаил', 'кандидат', 'доцент', '01.04.2014', 4);
INSERT INTO LECTURER (ID, LAST_NAME, FIRST_NAME, SCIENT_DEGREE, ACADEM_STATUS, START_DATE, CHAIR_ID)
VALUES (8, 'Легощин', 'Константин', 'доктор', 'профессор', '23.11.2003', 5);
INSERT INTO LECTURER (ID, LAST_NAME, FIRST_NAME, SCIENT_DEGREE, ACADEM_STATUS, START_DATE, CHAIR_ID)
VALUES (9, 'Ким', 'Лидия', 'доктор', 'профессор', '04.06.2013', 6);
INSERT INTO LECTURER (ID, LAST_NAME, FIRST_NAME, SCIENT_DEGREE, ACADEM_STATUS, START_DATE, CHAIR_ID)
VALUES (10, 'Бардина', 'Людмила', 'кандидат', 'доцент', '13.08.2016', 6);
INSERT INTO LECTURER (ID, LAST_NAME, FIRST_NAME, SCIENT_DEGREE, ACADEM_STATUS, START_DATE, CHAIR_ID)
VALUES (11, 'Кокорина', 'Людмила', 'кандидат', 'доцент', '16.07.2015', 6);
INSERT INTO LECTURER (ID, LAST_NAME, FIRST_NAME, SCIENT_DEGREE, ACADEM_STATUS, START_DATE, CHAIR_ID)
VALUES (12, 'Зеленин', 'Алексей', 'доктор', 'профессор', '23.05.2008', 7);
INSERT INTO LECTURER (ID, LAST_NAME, FIRST_NAME, SCIENT_DEGREE, ACADEM_STATUS, START_DATE, CHAIR_ID)
VALUES (13, 'Нестеров', 'Даниил', 'кандидат', 'доцент', '14.03.2021', 7);
INSERT INTO LECTURER (ID, LAST_NAME, FIRST_NAME, SCIENT_DEGREE, ACADEM_STATUS, START_DATE, CHAIR_ID)
VALUES (14, 'Юматов', 'Константин', 'кандидат', 'доцент', '27.08.1999', 8);